# Radarr - Movie Management

services:
  radarr:
    image: ${RADARR_IMAGE}:${RADARR_TAG}
    env_file:
      - ../.env.defaults
      - ../.env.local
    container_name: radarr
    
    user: ${RADARR_UID}:${MEDIACENTER_GID}
    networks:
      mediacenter:
        ipv4_address: 172.30.0.9
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "--connect-timeout", "3", "http://localhost:7878/ping"]
      interval: 5s
      timeout: 4s
      retries: 4
      start_period: 5s
    environment:
    - PUID=${RADARR_UID}
    - PGID=${MEDIACENTER_GID}
    - UMASK=002
    - TZ=${TIMEZONE}
    tmpfs:
    - /tmp:mode=770,noexec,size=50M,uid=${RADARR_UID},gid=${MEDIACENTER_GID}
    - /logs:mode=770,size=100M,uid=${RADARR_UID},gid=${MEDIACENTER_GID}
    volumes:
    - ${ROOT_DIR}/config/radarr-config:/config
    - ${ROOT_DIR}/data:/data
    ports:
    - ${RADARR_PORT}:7878
    restart: on-failure:5
    logging:
      driver: local
      options:
        max-file: '5'
        max-size: 10m
    labels:
    - traefik.enable=true
    - traefik.http.routers.radarr.rule=Host(`${RADARR_TRAEFIK_NAME}.${DOMAIN_NAME}`)
    - traefik.http.routers.radarr.entrypoints=web
    - traefik.http.services.radarr.loadbalancer.server.port=7878
    depends_on:
      prowlarr:
        condition: service_healthy
        restart: true
